-- 코드를 입력하세요
SELECT B.PRODUCT_CODE, SUM(A.SALES_AMOUNT * B.PRICE) AS SALES
FROM OFFLINE_SALE A JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES DESC, B.PRODUCT_CODE ASC